### ISSUE TITLE
Test Builds #6

### ISSUE THREAD

**Issue by Spookcity** [Spookcity/ROMS-G800F#22]
A continuation of #10, #18, #19, #20 and #21

**Comment by Spookcity** [comment]
**Spookcity_Kernel-N - Test v4.0a**

**Changes:**

- **Removed ROW I/O scheduler** ( until I can hopefully fix it)
- **Added I/O scheduler switcher by sultanxda** (changes the I/O scheduler for a specified request queue to Noop when the screen turns off in order to improve power consumption while the screen is off
- **Added PIE net scheduler**
- **Added support for USB keyboards** ( You need [This app](https://play.google.com/store/apps/details?id=remote.hid.keyboard.client) to use it.
- **Properly enabled faux123's powersuspend v2.5**
- **Added dynamic fsync**
- **Added optimization flags for the GPU**
- **Enabled AIO**
- **Fixed alucard governor** (hopefully)
- **Fixed ondemandplus governor** (hopefully)
- **Fixed bluactive governor** (hopefully)
- **Added intelliactive governor** (by faux123)
- **Added intelliplug hotplug driver** (by faux123)
- **Added thunderplug hotplug driver** (by  varun.chitre15)
- **Added Dynamic management of dirty page writebacks** (allows to have two different intervals for dirty page writebacks and to dynamically manage them when the system has been resumed (it's active) or when has been suspended - Not adjustable via garaks kernel adiutor app)

**Other things of note**

- **lib/int_sqrt.c: optimize square root algorithm**
- **af_unix: speedup /proc/net/unix**
- **wireless - bcmdhd - reduce scan dwell time to reduce power usage**
- **bcmdhd reduce wakelocks**
- **readahead: make context readahead more conservative**
- **block/partitions: optimize memory allocation in check_partition()**
- **power: make sync on suspend optional**
- **block: bfq-iosched: tuning for SSD** (thanks to anarkia1976)

- Please give feedback [Here](https://github.com/Spookcity/ROMS-G800F/issues/12) and **NOT** in the XDA thread for test builds. Otherwise it will be come very confusing. Thanks!

**Download** [Spookcity_Kernel-N_v4.0a](https://drive.google.com/open?id=0B_rGv18gTmnVbDYxMU5NdUdmc2M)
**Download** [Spookcity_Kernel-N_v4.0a-1500mhz](https://drive.google.com/open?id=0B_rGv18gTmnVVWM2TUtLcHh4Yzg) (untested)

**Comment by HaxXorHardy** [comment]
hi @Spookcity 
i installed Beanstalk rom(newest)
then spookcit-kernel-4.0a
then gapps nano
then superSU
one after one with TWRP
Fresh install and it reboots after 3 mins of use.
is this correct sequence?
idk what is the fault :(

now i tried a fresh install:
First beanstalk rom
then the kernel.
it is still the same problem

here is the log from the second try.
[log.txt](https://github.com/Spookcity/ROMS-G800F/files/1231235/log.txt)
[log1.txt](https://github.com/Spookcity/ROMS-G800F/files/1231236/log1.txt)

**Comment by Spookcity** [comment]
@HaxXorHardy Hmm,interesting. I'll try to have a look at the log when I'm home if I have some time. I've just been rather busy. The sequence your flashing sounds fine. I can only offer a quick suggestion right now,and that's to try and eliminate the cause one by one. So,only flash the ROM. See how it goes. Then maybe flash gapps and so on. You may be able to at least figure out the cause like that.

_Sent from my Samsung SM-G800F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by HaxXorHardy** [comment]
It is after flashing the kernel. But idk what the reason is. I use the newest twrp  and only flashed Rom and kernel like the logs in my first comment they are only Rom and kernel.

_Sent from my Samsung SM-G800F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Spookcity** [comment]
@HaxXorHardy Just had a quick look at your logs. Sorry I was busy yesterday..but is/was your device encrypted? I only ask because this is the only thing that really stood out to me in the logs 
"Cryptfs : Cannot remove dm-crypt device"

**Comment by HaxXorHardy** [comment]
@Spookcity Yes it was encripted but i flashed the Stock rom cause i got a realy strange error: 
![14985081336574](https://user-images.githubusercontent.com/1397712/29484555-83527fd0-84c1-11e7-8852-7c376402098c.jpg)
after press "reset Phone" it loads twrp and trys to delete data cache etc(default settings)
the only posibility was odin mode cause twrp was not able to mount the partitions.

Do you think that is maybe the fault and how can i fix it?

**Comment by Spookcity** [comment]
@HaxXorHardy I do think it has something to do with it yes. If it is fully due to that I'm unsure.
I'm trying to think of a solution that you haven't already tried and don't really know off the top of my head. I'll have to give it some thought. Perhaps someone else has an idea?

_Sent from my Samsung SM-G800F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by HaxXorHardy** [comment]
@Spookcity i dont know how this works, but maybe repartitioning vor deleting this thingy is an Option? I have not tryed any solution, cause I never had any problems wit this. Hmm maybe encript end decript again?

_Sent from my Samsung SM-G800F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Spookcity** [comment]
@HaxXorHardy I will be honest,I really am very unsure and don't want to give you bad advice. It's a strange issue. Hopefully someone else has some clue because I really don't. If not,maybe post the issue on XDA? Maybe someone there can help. I've never messed with encryption on a phone in any way, so yeah I'm not very qualified to answer this.

_Sent from my Samsung SM-G800F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Spookcity** [comment]
Hey can anyone test the intelliactive CPU governor for awhile? I was getting random reboots with the last test version of my kernel. I had not messed with voltages or much else. I have since switch CPU governors and its yet to happen. Just curious if anyone can confirm this. Thanks!

**Comment by Mikahlo** [comment]
@Spookcity I did just that, see my repo for logs with intelliactive. Do you need a dmesg or modem log? I had the random reboot once with zzmove and profile 4 also. The logs are kind of useless I guess. Isn't there a way to get a more precise log of what happened when the os crashed?

**Comment by Spookcity** [comment]
@Mikahlo Thank you very much! I will have a look hopefully tomorrow. I've just been lacking time recently to look into this further. I've also grabbed a log from my reboot with intelliactive. Again,kernel panic. No surprise. It might have to do with me changing the HZ to 300 from 100...or a suspend thing. Intelliactive def seems to be the cause though. I've not had a single reboot until using it.

As far as better logs. I'm really not sure honestly. I've applied some patches to make the kernel log easier to interpret, but I'm really not sure. I know if I was able to interpret the stack dump it'd be a lot easier,but I need to learn this. I'm still really new to Android stuff really. Most of my knowledge is just carry over from my love of Linux...and I've obviously learned some android,but still,long way to go. Thanks again for the logs.

Edit:
@Mikahlo Had sometime to look over your logs. The logcat showed nothing that really stood out to me.
Your kernel log again shows a kernel panic. Hopefully I will have some time this week to try to figure out how to properly interpret the backtrace. Then I will know the exact cause. From my understanding though it is related to a timer problem.

_Sent from my Samsung SM-G800F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by jimmy999x** [comment]
Good evening everyone, I have not been around for a long time, I have been busy, I have a big question, I have seen that bliss rom and lineageos already started working with version 8.0, when they think that it is ready for our device? I speak of the source code, I am anxious to test android 8.0

**Comment by Spookcity** [comment]
@jimmy999x  Yeah,I noticed this as well. I had a look at SlimROMS 8.0 manifest and at this point they are only pulling the AOSP repo's. Same with Lineage. They are pulling some of their own,but they are all 14.1. So until this changes I see no point in even attempting a build....which I believe is going to be full of problems for our device sadly :(

**Comment by jimmy999x** [comment]
why? Some incompatibilities?

**Comment by Spookcity** [comment]
@jimmy999x Well,with every new release there are changes that will nearly certainly require at least some changes to the device trees. From what I've read about Android O there are some rather significant changes. This could be a challenge. Tobias aka hennymcc is the one who has fixed and created the majority of the fixes and patches for the trees. It's not an easy thing to do and requires lots of debugging. 

The only real way to go about it if you don't know any programming is to just build. Get an error. Try to fix it and so on. Could be very time consuming.

_Sent from my Samsung SM-G800F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by jimmy999x** [comment]
Unfortunately not being programmed in android, but if I can collaborate with a server so that they can perform their tests and others, it has good compilation times and also internet connection

**Comment by Spookcity** [comment]
@jimmy999x Thanks,that is certainly appreciated and could be useful. I'm not sure. For myself I am still in the very beginnings of learning java and cpp,so it would probably be very difficult..or at least exceptionally time consuming for me to do it. Hopefully hennymcc has plans to work on it at some point. I'm not sure,but I would also understand if he doesn't as it is really time consuming.

_Sent from my Samsung SM-G800F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Spookcity** [comment]
**Spookcity_Kernel-N - Test v4.0b**

This is attempt number one to try to solve some of these random reboots that some,myself included,are experiencing with the last build. Apologies for taking so long to try and get this resolved. I've just been very busy.Hopefully this will have some effect as I'm not too sure what step 2 will be at this point. I guess looking into suspend related things.

**Changes**

- Reverted a few HZ related commits

**Download**
[Spookcity_Kernel-N_v4.0b](https://drive.google.com/open?id=0B_rGv18gTmnVVDM1bWR5TUJ1a1E)
[Spookcity_Kernel-N_v4.0b-1500mhz](https://drive.google.com/open?id=0B_rGv18gTmnVN3hEWXJQSlZUU3M)

**Comment by hard-sat** [comment]
RR-N-v5.8.4-20170813-kminilte-Unofficial
Spookcity_Kernel-N_v4.0b-1500mhz (v3.0a, v4.0a, v4.0b)
kerneladiutor-update-Quark.44.BHB27-Mod or Kernel+Adiutor+v0.9.71.1P(239)
new frequency, it is impossible to change tension of frequencies ((
v3.0 have no new frequency
![screenshot_20170817-221202_](https://user-images.githubusercontent.com/28715316/29861126-de71db56-8d70-11e7-9bc8-8b2e5c8550b4.jpg)
I thank

**Comment by Spookcity** [comment]
@hard-sat Hmm, I have no clue why this would be. No one else has reported this to me and I have no issues. I have used a few different versions of kernel adiutor as well. I'm not sure what to say. I will try the 1500MHZ version and see. I have not tested these. Perhaps I messed something up.

Edit:
Also,that bizarre frequency seems to be "normal" I'm not sure why,but I have had that a time or two as well. Something I'll look into also.

**Comment by hard-sat** [comment]
and v.3 perfectly works! 
something is badly changed in the version of century v.3a and, as a result, the subsequent versions.
I thank

**Comment by Spookcity** [comment]
@hard-sat You are right. It's only the 1500MHZ version,but changing voltages indeed does not work with version 4.0b..Probably the last few versions as well. I obviously messed something up. I will try to fix it when I have some time.

_Sent from my Samsung SM-G800F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Mikahlo** [comment]
@Spookcity No random reboots with Spookcity_Kernel-N - Test v4.0b. I guess you reverted the correct commits. I didn't mess with kernel-adiutor at all. So I was using the default settings. The battery lifetime is great like the previous versions. I will try other governors the next days and hope for the best :)

**Comment by Spookcity** [comment]
@Mikahlo Great news and many thanks for the feedback! Hopefully this will be behind me now so I can release a stable v5.0 on XDA and work on other test builds to release on here.

_Sent from my Samsung SM-G800F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by hard-sat** [comment]
**Spookcity**, THANKS for Spookcity_Kernel-N_v5.0-1500, everything perfectly works and tension changes)) 
and it is possible to make FM-radio also? worked on the Android 4... ))
I thank))

**Comment by Spookcity** [comment]
@hard-sat Glad to hear the voltage control is indeed fixed. As far as FM radio. A month or more ago I tried very hard to figure this out. I even downloaded the KK kernel sources to try to build the module.I tried a few different radio apps,but none would work. I have to say I think FM radio for our device is a lost cause.

_Sent from my Samsung SM-G800F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by hard-sat** [comment]
it is a pity, I thank))

**Comment by Spookcity** [comment]
@hard-sat I agree,it would be nice. I'm just not real sure what else I can try. Perhaps if I have some free time I will revisit it. Maybe I can think of another idea.

_Sent from my Samsung SM-G800F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by hard-sat** [comment]
very pleasantly to communicate with you, good luck, I thank))

**Comment by Spookcity** [comment]
@hard-sat Same to you :)

_Sent from my Samsung SM-G800F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by hard-sat** [comment]
we wait for your grandiose decisions! ))

**Comment by hard-sat** [comment]
**Spookcity**, hello. I read on XDA about complaints to unauthorized resets with your kernel.  I had such problems too. I updated the program of the modem. My resets ended. The program of the modem is updated separately programs of system. Can do it and will help ))

**Comment by hard-sat** [comment]
[Basebands / Modems] SM-G800F](https://forum.xda-developers.com/galaxy-s5-mini/general/baseband-sm-g800f-t3354355)
maybe will help))

**Comment by Spookcity** [comment]
@hard-sat  Hey,thanks a lot! I always appreciate the help. I'm not sure if that's the issue for them or not,but it could be. I will mention it to them.Thanks.

**Comment by jimmy999x** [comment]
I've noticed that hennymcc is working on LOS 15.0, that's very good news! :) When I have time, I will try to compile some test version for you

**Comment by StanNL** [comment]
@jimmy999x That would be amazing!! That way, we could also help henny a little bit by testing everything. I'll volunteer as a guinea pig :)

**Comment by StanNL** [comment]
@jimmy999x Henny just made some "fix compilation" (?) commits, which will probably make the compilation easier, so good luck!

**Comment by Spookcity** [comment]
It is indeed great news that Tobias has started to work on Android O for our device. We are very lucky. At this point,last I heard he has successfully got it to build,but it doesn't boot. I've been lacking the time lately to do much of anything android related,but hopefully soon I will try to see if I'm able to lend a hand in some small way.

_Sent from my Samsung SM-G800F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by jimmy999x** [comment]
![image](https://user-images.githubusercontent.com/21678167/30515529-eab6b606-9aff-11e7-98e9-e44091f6a8d4.png)
I can not compile roms, for this problem, any ideas?

**Comment by Oleggluk** [comment]
I understand correctly, the development of RR for android N is discontinued? https://plus.google.com/communities/109352646351468373340
@jimmy999x 
Could you, when will be the time, make the final version?

**Comment by jimmy999x** [comment]
yesterday I tried to compile roms for the s5 and s5 mini, but due to the recent changes that were made, I could not do it, apparently I have to discard some commits

**Comment by Spookcity** [comment]
@jimmy999x The error you posted earlier I would assume could be fixed by finding that permissions.xml file...Or you could comment it out wherever it's called for (BoardConfig.mk,device.mk) Not sure what that file does specifically though,so it could cause issues if done this way.

On a side note: I finally had some free time today. I successfully built crDroid 8.0,but as with LOS 15 it doesn't boot. It seems to be possibly related to the hwcomposer. If I have any time this week I'll try to talk to Tobias and work on it some more.

_Sent from my Samsung SM-G800F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by friedensfurz** [comment]
@jimmy999x Can you please update RR?  Thanks:grinning:

**Comment by Spookcity** [comment]
@friedensfurz If @jimmy999x  is too busy and doesn't have the time I may have the time to try to build an update for RR over the weekend or early next week.

_Sent from my Samsung SM-G800F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by jimmy999x** [comment]
Sorry guys, I do not have the same time as before, lately I'm very busy with the university

**Comment by friedensfurz** [comment]
@jimmy999x No problem, take your time. @Spookcity might build RR when he has some time:grinning:

**Comment by Spookcity** [comment]
@friedensfurz i indeed will build an update. Things have been pushed back some due to me working on LOS 15 (which Tobias has now posted up on XDA) So, I will try to get RR updated later in the week....As well as a new test build of my kernel.

**Comment by Spookcity** [comment]
Well,I found a little time to build RR,so here ya go. AFH won't let me log in,so I have put it on my GDrive for now. I will probably add it to the main RR XDA thread too at some point as Zocker added me as a contributor.

[RR-5.8.5-FINAL](https://drive.google.com/open?id=0B_rGv18gTmnVYXhJOTdERGpOeFk)

**Comment by HaxXorHardy** [comment]
please update Beanstalk rom! i love this rom it works perfect for me! <3<3<3

**Comment by Spookcity** [comment]
@HaxXorHardy I am going to build an update for slim today. Then Beanstalk will be my next build.

**Comment by HaxXorHardy** [comment]
@Spookcity ty you are the best! :heart_eyes:

**Comment by Spookcity** [comment]
@HaxXorHardy Beanstalk updated. Have a look at the main post on XDA for some important details.
[XDA](https://forum.xda-developers.com/galaxy-s5-mini/development/rom-beanstalk-7-nougat-t3585327/)

**Comment by Oleggluk** [comment]
@Spookcity The calm before the storm? What awaits us in the new test version of the kernel?)

**Comment by Spookcity** [comment]
@Oleggluk Yes, I have just spent my rather limited free time the last little while trying to help out as much as I'm able with some LOS 15 issues. I was actually going to release a test build today. I built it,but it throws an error while flashing about the image being too large for the boot partition. Which is strange,but I've obviously messed something up. I will try my best to look into it and hopefully get it sorted in the next few days.

_Sent from my Samsung SM-G800F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Spookcity** [comment]
**Spookcity_Kernel-N - Test v5.1**

**Changes:**

- **Added MSM Sleeper hotplug**
- **Reduced vm_swappiness from 60 to 20**
- **Added intellidemand governor**
- **Added autoSMP hotplug**
- **Added CPU boost driver**
- [**Proc: much faster /proc/vmstat**](https://github.com/Spookcity/android_kernel_samsung_kminilte/commit/f131b7bbb5e82401486e479fb15120874428a285)
- [**Cpufreq: Persist cpufreq time in state data across hotplug**](https://github.com/Spookcity/android_kernel_samsung_kminilte/commit/464a44ca9b8e19dc611c9261a54cfc7710e629f2)
- **Reverted "enable arch power"** (There will soon be a switch to enable or disable this)

There are other features that I have already added (CPU gov's etc) that are currently partially broken,so they are not included in this build. I will hopefully have more time in the near future to work on this kernel.

**Download** [Spookcity_Kernel-N_v5.1](https://drive.google.com/open?id=0B_rGv18gTmnVMzZGeWFvbFlsR28)
**Download** [Spookcity_Kernel-N_v5.1-1500mhz](https://drive.google.com/open?id=0B_rGv18gTmnVaHVsY2tOOWpBUVk) (untested)

**Comment by hard-sat** [comment]
here and problem with Spookcity_Kernel-N_v5.1-1500mhz
tension on 1500mhz isn't regulated ((
![screenshot_20171003-184823_1](https://user-images.githubusercontent.com/28715316/31135292-36199ac6-a86d-11e7-8b41-5071168e6c97.png)
help please, I thanks

**Comment by Spookcity** [comment]
@hard-sat Ugg,sorry about that. This is the same problem as with the last 1500mhz version. Hopefully I can remember how I fixed it. I have been pretty busy,but will look into it and release a fixed version as soon as I have some time.

Edit: 
@hard-sat I think I have fixed this issue. The new build is in the same post above. Hope it works now.

_Sent from my Samsung SM-G800F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by hard-sat** [comment]
this problem is solved, we wait for updates, I thank ))

**Comment by friedensfurz** [comment]
@spookcity With 5.1, still Crashes within minutes :( I really think it's a F2FS problem, can you / somone try to use this kernel with data and cache as F2FS? Thx

**Comment by Spookcity** [comment]
@friedensfurz Hmm,that's a shame. Thanks for letting me know. I have been really busy lately with real life things and the limited free time I've had has been spent trying to sort out some audio issues with LOS 15. I'm not really sure what I would have done to cause this problem. Particularly with F2FS. I will need to have a look into. Which I will when I have the time.

_Sent from my Samsung SM-G800F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Oleggluk** [comment]
@Spookcity Los15 is interesting. Calls already working? I tested the prealph version a little. And what are the problems with sound? I remember there the music played well. I also noticed a lot of settings for bluetooth in the developer parameters, but there was no way to check it.

**Comment by Spookcity** [comment]
@Oleggluk Yes,Tobias fixed the ril problem,so calls work now. Sound was working fine,but something has changed and no longer works. I've tried many things to try to figure this out (reverting things,applying found patches etc.) with no luck so far. It's very confusing. I'm sure Tobias will figure it out though when he has the time.


_Sent from my Samsung SM-G800F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by vonico** [comment]
so what is working and what isn't now in LOS 15? I have a bit of free time and I could install again Linux and try to build to see what's (not) working now

**Comment by Spookcity** [comment]
@vonico The only thing that doesn't work in my testing and useage is audio (ringtones, music player,etc) Phone calls work fine now. Audio worked before,but no longer does for some reason. I've given myself a headache trying to sort that out,so I've taken a break. I'm sure its something simple that I'm just overlooking. Tobias is away,but I'm sure he'll figure it out when's he's back if I'm unable. 

Edit:
Some things I've not used,but just thought about and am pretty sure still don't work are GPS and NFC. Camera does now though.

_Sent from my Samsung SM-G800F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by vonico** [comment]
@Spookcity great!
Can somebody build LOS 15? I am too busy to do it myself this weekend and would like to at least try it out!

**Comment by Spookcity** [comment]
@vonico I've built LOS15 many times in the last few days. Luckily I have sorted out the audio problem and have built yet again.
You can test it out no prob: [lineage-15.0-20171006-UNOFFICIAL-kminilte](https://drive.google.com/open?id=0B_rGv18gTmnVQ0I4Y2FFVjZJZEU)

Edit: I also applied a patch for home button wake as it was driving me insane hah

**Comment by vonico** [comment]
@Spookcity already downloading
Thank you very much! 😊😊

**Comment by Oleggluk** [comment]
@Spookcity @vonico 
Does anyone have problems with memory on los15? Applications do not see memory and a memory card. The camera also does not see the memory.

**Comment by Spookcity** [comment]
@Oleggluk Interesting. The camera, you are right,has a problem with picking it up. The camera still needs more work. My internal and external card are picked up fine though other than the camera. 

Edit:
I need to test more. I've not tried many apps. I now understand what you're saying. I will test this out later as I'm currently away,so I'm using another ROM.
Feedback like this is very good though and will help in fixing things.

_Sent from my Samsung SM-G800F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Oleggluk** [comment]
@Spookcity My any installed applications do not see memory and a memory card.

Редактировать: I'll now try to make a complete format with the removal of all files

**Comment by Spookcity** [comment]
@Oleggluk Yeah,I realized that's what you meant after I read your post better. I don't think I tested this,so this may indeed be an issue. I'll flash it later,test and grab a log and go from there. Thanks for reporting

_Sent from my Samsung SM-G800F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Oleggluk** [comment]
@Spookcity A complete deletion of all files from the phone does not help. Applications do not see memory or write that there is no access.

**Comment by Spookcity** [comment]
@Oleggluk OK,this explains the camera issue then. I guess it's a system wide issue. Did you have this problem when you tested the build on XDA?

_Sent from my Samsung SM-G800F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Oleggluk** [comment]
@Spookcity I did not use this version for a long time, as there were constant reboots. But then I managed to install x-plore and from it a couple of applications., So x-plore saw the memory.

**Comment by Spookcity** [comment]
@Oleggluk OK,yeah the reboots were caused by a kernel issue that Tobias fixed. I'll try to look into the storage issue soon though.

_Sent from my Samsung SM-G800F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by vonico** [comment]
@Spookcity my camera also says to insert an sd card before being able to use it, although I have one.
I also have trouble restoring my whatsapp chats backup, but I guess that doesn't have that much to do with the ROM though...
other than that, everything else is working really smoothly and without any issues at all :)

That said, I do miss some personalization options such as locking the lock screen to only portrait, or to configure the button's behavior, but again I guess that's just not implemented in Lineage yet.

**Comment by Oleggluk** [comment]
@Spookcity People are asking to make the kernel support TTL fixing. Some operators block the distribution of the Internet, but there are instructions on how to get around this. But the kernel must support the fixation of ttl.
Quote: "On the operators of the Big Three, as well as Tele2, in contrast to the Iota TTL must be fixed, not changed.
And it's on 64, and it's on the distributing. Others do not work. In addition, this device should be supported at the kernel level: if there is no TTL line in the file / proc / net / ip_tables_targets, then you need to change / compile the kernel.

**Comment by Spookcity** [comment]
@Oleggluk Yeah, I don't know much about this,but thanks fro providing the info. I will certainly look into it. It sounds rather easy from what you wrote. 

@vonico Yeah.I am going to try to look into this storage issue later. LOS 15 is still in the early days,so it is missing a lot of features. I built AICP 13 as well,but it is simply LOS 15 at this point. In time more things will come.

**Comment by Oleggluk** [comment]
@Spookcity Is AICP 13 also a memory issue?

**Comment by Spookcity** [comment]
@Oleggluk Honestly I'm not sure. I didn't test it. I would assume so though as it must be a device issue. Hopefully I'll have a little time later today to see about this.

_Sent from my Samsung SM-G800F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Oleggluk** [comment]
@Spookcity I have a lot of time today, I can check if you give me a link

**Comment by Spookcity** [comment]
@Oleggluk I don't have the AICP build any longer. I still have the sources though,but I was talking with Tobias and his build (the one on XDA) does not have the problem with memory/storage. That may make it easier. Either I just did something wrong...A new patch that has been added since his build or perhaps the sources have caused this issue. I think its more likely one of the first 2. I am going to try to build again shortly and see if I am able to sort it out. I will keep you posted.

**Comment by Spookcity** [comment]
@Oleggluk Any particular apps that don't detect storage? Aside from the camera. I would like to test. I tested the browser and it was not a problem.

**Comment by Oleggluk** [comment]
@Spookcity for example, the x-plore file manager does not show partitions of internal and external memory at all.

**Comment by Spookcity** [comment]
@Oleggluk OK thanks,I just installed MiXplorer and indeed same thing.

Edit: Well kinda. It doesn't show the internal or external storage,but if I click to show images or audio for example,it displays everything correctly.

**Comment by vonico** [comment]
@Spookcity I tried downloading a pdf and it also told me that no sd card was detected.
Also in whatsapp, I get an error when downloading pictures, besides from not being able to restore the backup I made...

**Comment by Oleggluk** [comment]
@Spookcity It's strange, the system sees well the memory and the memory card, extracts the memory card without problems, all the volume readings and the names are correct., But somewhere something prevents the applications from seeing the memory and writing to it. I hope it will not be difficult to fix it

**Comment by Spookcity** [comment]
@vonico OK,thanks for the info. Interesting. I downloaded something via the browser app and had no issues.

@Oleggluk You are exactly right. This is exactly whats happening. I will mess with it a little more and see if I'm able to sort it out.

**Comment by vonico** [comment]
@Spookcity good luck! When you come up with a new build I'll be ready to try it out! :)

**Comment by Spookcity** [comment]
Alright,well I was unable to solve this yet. Its a strange issue. I have downloaded many things via the browser without issue. There's certainly something strange about it,but the logs didn't really show anything. I'm off for now,but if anyone can get any useful logs of the problem,particularly WhatsApp or similar that'd be great and I'll gladly have a look and try some other things tomorrow.

_Sent from my Samsung SM-G800F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Oleggluk** [comment]
@Spookcity But the program for logs can not save it as it will not see the memory)). Do I have to do this via adb on my computer? What commands need to be entered in adb for the correct log and how to save it in txt?

**Comment by vonico** [comment]
I got a logcat when downloading a picture in Whatsapp and another log when downloading the file in chrome
[logcat_whatsapp.txt](https://github.com/Spookcity/ROMS-G800F/files/1366246/logcat_whatsapp.txt)
[logcat_chrome.txt](https://github.com/Spookcity/ROMS-G800F/files/1366247/logcat_chrome.txt)

EDIT:
idk if this is related, but I also see these lines quite often in the log just with the phone plugged in:
```

10-07 18:01:46.492 13846 14107 E android.hardware.memtrack@1.0-impl: hw_get_module memtrack failed: -2
10-07 18:01:46.494 13846 14107 E memtrack: Couldn't load memtrack module
10-07 18:01:46.494 13846 14107 W android.os.Debug: failed to get memory consumption info: -1
```

**Comment by Spookcity** [comment]
@vonico Many thanks! The lines you posted are not relevant to this issue I don't think. I'll have a look at your logs when I'm home later. Thanks again!

_Sent from my Samsung SM-G800F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by vonico** [comment]
@Spookcity I think this one is more detailed:

```
10-07 18:46:09.388  2052  3773 I AudioHardwareTinyALSA: AudioStreamOutALSA::write setDevice
10-07 18:46:09.388  2052  3773 E AudioHardwareTinyALSA: int android::AudioHardwareTinyALSA::open_hdmi_driver() cannot open video16 (-1)
10-07 18:46:09.388  2052  3773 D AudioHardwareTinyALSA: OutALSA::setDevice: mode = 0, newDevice=0x2, currentDevice=0x2 ,force= 0
10-07 18:46:09.388  2052  3773 D AudioHardwareTinyALSA: OutALSA::setDevice: mDevice 0x2, newDevice = 0x2
10-07 18:46:09.388  2052  3773 D AudioHardwareTinyALSA: setOutputVolume
10-07 18:46:09.388  2052  3773 D TinyUCM : setModifier Normal, en=1
10-07 18:46:09.388  2052  3773 E TinyUCM : modifier doesn't exists any more
10-07 18:46:09.388  2052  3773 I AudioHardwareTinyALSA: OutALSA::setDevice: mHandle NULL mode[0], Device[00000002]
10-07 18:46:09.389  2052  3773 I AudioHardwareTinyALSA: Open: mDefaults->direction=0 device=3
10-07 18:46:09.389  2052  3773 D AudioHardwareTinyALSA: Channel: 2, Samplerate: 48000, Format: 0, Peroid Size: 960, Period Count: 4
10-07 18:46:09.389  2052  3773 D AudioHardwareTinyALSA: ALSAStreamOps::open: after pcm_open: Card: 0, Device: 3
10-07 18:46:09.389  2052  3773 I AudioHardwareTinyALSA: before pcm_prepare
10-07 18:46:09.389  2052  3773 D AudioHardwareTinyALSA: [NXP] set PcmInterface is called
10-07 18:46:09.390  2052  3773 D AudioHardwareTinyALSA: setPcmInterface: Stream=0x1, iSamplerate=8000++
10-07 18:46:09.390  2052  3773 D AudioHardwareTinyALSA: setPcmInterface--
10-07 18:46:09.401  2052  2187 D AudioFlinger: mixer(0xaf983d40) throttle end: throttle time(32)
10-07 18:46:09.520 19384 24389 I System.out: Error inflating SSL session: error:100000a0:SSL routines:OPENSSL_internal:INVALID_SSL_SESSION
10-07 18:46:09.699  2045  2045 I display : [DYNAMIC_RECOMP] GLES_2_HWC by high FPS(60)
10-07 18:46:10.254 19384 19452 D WhatsApp: LL_D W [8926:WriterThread] SEND <iq id='00' xmlns='w:stats' type='set' to='s.whatsapp.net'><add t='1507394770'>WAM%03%88!%01%07SM-G800%20i0%0b%02%80%0d%0fsamsung-SM-G800%80%0f%058.0.0H%8f%02%c0%00%88%ef%01%08kminilteP/%a5%03%d9Y%80%11%082.17.368H%b1%02%dc%07%20%15%20%178y%06%038{%06%02%88%1f%01%07samsung)%16%02%12%01B%02%15%02V%03%b5%c0%0f%00)%cc%01"%01"%02F%03%14%02)%de%01"%01%12%03%12%04"%052%06%026%07%02)%c2%01"%012%02%02%12%04"%05F%06f%05P/%a6%03%d9Y)%cc%04%82%01%03mmgB%03u%02B%04%94%00%16%05P/%a7%03%d9Y%19%c8%012%01%022%02%0a%12%04%12%11%12%08%82%09%03mmg%12%0b%12%0c2%10%04B%05%18%02R%06%dd%a8%01%00B%0d%f1%012%0e%06B%0f%ff%01%12%132%14%02%16%15)P%03"%012%02%02B%03%ca%02V%04[%df%00%00P/%a8%03%d9Y%19%c8%012%01%022%02%0a%12%04%12%11%12%08%82%09%03mmg%12%0b%12%0c2%10%04B%05?%01R%06%8b%a1%01%00B%0d*%01"%0eB%0f<%01%12%132%14%02%16%15P/%aa%03%d9Y%19%c8%012%01%022%02%0a%12%04%12%11%12%08%82%09%03mmg%12%0b%12%0c2%10%04B%05v%03R%06"/%02%00B%0de%03"%0eB%0fs%03%12%132%14%02%16%15P/%ab%03%d9Y%19%c8%012%01%022%02%0a%12%04%12%11%12%08%82%09%03mmg%12%0b%12%0c2%10%04B%05%1f%01B%06q=B%0d%0d%01"%0eB%0f%1c%01%12%132%14%02%16%15P/%ad%03%d9Y%19%c8%012%01%022%02%0a%12%04%12%11%12%08%82%09%03mmg%12%0b%12%0c2%10%04B%05%1d%01R%06%13%99%03%00B%0d%0b%01"%0eB%0f%1b%01%12%132%14%02%16%15P/%d8%03%d9Y)V%03"%02"%03%12%07"%08F%0b9%03P/%e0%03%d9Y)%de%01"%01%12%03%12%04%12%052%06%02&%07)%c2%01"%01"%02%12%04%12%05F%06%a4%02P/%d2%04%d9Y%19%c8%012%01%022%02%0a%12%04%12%11%12%08%82%09%03mmg%12%0b%12%0c2%10%04B%058%03R%06%dd%a8%01%00B%0d%03%03%12%0eB%0f%16%03%12%13"%14%16%15</add></iq>
10-07 18:46:10.352  2045  2045 D SurfaceFlinger: duplicate layer name: changing com.whatsapp/com.whatsapp.Conversation to com.whatsapp/com.whatsapp.Conversation#1
10-07 18:46:10.372  2045  3775 W GrallocMapperPassthrough: buffer descriptor with invalid usage bits 0x400
10-07 18:46:10.382 19384 19395 I zygote  : Background concurrent copying GC freed 32479(2MB) AllocSpace objects, 10(408KB) LOS objects, 49% free, 4MB/8MB, paused 5.202ms total 127.725ms
10-07 18:46:10.410  2045  2647 W GrallocMapperPassthrough: buffer descriptor with invalid usage bits 0x400
10-07 18:46:10.445  2045  2109 W GrallocMapperPassthrough: buffer descriptor with invalid usage bits 0x400
10-07 18:46:10.511 19384 24293 D WhatsApp: LL_D W [8954:ReaderThread] RECV <iq from='s.whatsapp.net' type='result' id='00'/>
10-07 18:46:11.218 19384 24305 W OkHttpClient: A connection to https://mmg.whatsapp.net/ was leaked. Did you forget to close a response body?
10-07 18:46:11.219 19384 24305 I chatty  : uid=10102(u0_a102) OkHttp Connecti identical 4 lines
10-07 18:46:11.219 19384 24305 W OkHttpClient: A connection to https://mmg.whatsapp.net/ was leaked. Did you forget to close a response body?
10-07 18:46:11.944  2045  2045 I display : [DYNAMIC_RECOMP] HWC_2_GLES by low FPS(2)
10-07 18:46:12.198  2045  2045 I display : [DYNAMIC_RECOMP] GLES_2_HWC by high FPS(59)
10-07 18:46:12.434  2052  2187 D AudioHardwareTinyALSA: Entering AudioStreamOutALSA standby mode
10-07 18:46:12.434  2052  2187 V AudioHardwareTinyALSA: closePcmInterface++
10-07 18:46:12.435  2052  2187 V AudioHardwareTinyALSA: closePcmInterface--
10-07 18:46:12.435  2052  2187 I AudioHardwareTinyALSA: Close mHandle:b1740420
10-07 18:46:15.144  2259  2294 E memtrack: Couldn't load memtrack module
10-07 18:46:15.144  2259  2294 W android.os.Debug: failed to get memory consumption info: -1
10-07 18:46:15.293  2259  2294 E memtrack: Couldn't load memtrack module
10-07 18:46:15.293  2259  2294 W android.os.Debug: failed to get memory consumption info: -1
10-07 18:46:15.371  2259  2294 E memtrack: Couldn't load memtrack module
10-07 18:46:15.372  2259  2294 W android.os.Debug: failed to get memory consumption info: -1
10-07 18:46:16.324  2045  2045 I display : [DYNAMIC_RECOMP] HWC_2_GLES by low FPS(3)
```

**Comment by Spookcity** [comment]
@vonico Thank you! I am not really sure what to think though. Your chrome log didn't show anything. The only thing that stands out to me in the Whatsapp logs are the OkHttpClient warnings. I'm unsure if this is the problem though. I was able to download things fine with the stock browser. I will try chrome and see what happens. I will also try to search about the memtrack errors. This seems to be some problem although I'm pretty sure not related to this.

Edit:
This seems to be this issue.From my Chrome log:
W/MediaScanner(  487): Error opening directory '/mnt/sdcard/.android_secure/', skipping: Permission denied

**Comment by vonico** [comment]
Hmm strange..
Maybe changing the permissions in recovery explorer fixes it?

**Comment by Spookcity** [comment]
I don't think that would fix it. I tried a few things via adb shell,but that didn't work either. I'll try to look more into it tomorrow if I have time. Its weird that it's not all apps though. Like the default browser works fine,but obviously Chrome,WhatsApp and the camera do not.

_Sent from my Samsung SM-G800 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by hard-sat** [comment]
all are silent, and I also did not note a problem ((
in Spookcity_Kernel-N_v5.1-1500mhz the problem with tension is solved, BUT new frequency 4294967 appeared again ((
help please!!! I thank
![screenshot_20171008-101719_](https://user-images.githubusercontent.com/28715316/31314881-58b42ac4-ac14-11e7-8adb-b05fe9b10c0a.png)

**Comment by Spookcity** [comment]
@hard-sat I guess I messed something up with the steps or something. I am rather busy,but will see if I can fix it soon.

**Comment by Spookcity** [comment]
So this storage issue with LOS 15 appears to be an sdcardfs problem. I have successfully download stuff with Chrome and my storage now shows up in MiXplorer as well. This was achieved by disabling sdcardfs. This is not a proper fix though.

**Comment by Oleggluk** [comment]
@Spookcity Want Want )

**Comment by vonico** [comment]
@Spookcity I think with this "fixed" I can use this as my main ROM. Thank you very much

**Comment by Spookcity** [comment]
@Oleggluk Haha,sure thing. [Here you go](https://drive.google.com/open?id=0B_rGv18gTmnVM0U5dTB2Mm94X2c)
Again,this is only a temporary workaround and not really a fix. Also,the camera is again broken. Not sure why. I'll need to see. Maybe I missed a patch.I would assume Whatsapp will also work with saving things now as well,but curious to hear as I've not tested. Maybe it cause other issues. I'm also not sure,but let me know.

**Comment by Oleggluk** [comment]
@Spookcity WhatsApp and Camera are working! If there are no serious errors, I will test all day.

**Comment by Spookcity** [comment]
@Oleggluk Great! Thanks for letting me know and would gladly appreciate any other findings you may notice. Thanks!

_Sent from my Samsung SM-G800 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by vonico** [comment]
@Spookcity camera does indeed not work, but the rest works fine. I restored the whatsapp backup without problems and now I'm back at the build from a couple of days ago.

**Comment by Oleggluk** [comment]
@Spookcity 
wi-fi works.
Mobile Internet works
The fingerprint scanner does not work.
G800 phone model without F
The GPS Status & Toolbox application v7.6.163 writes that there is no gps on this device))
The recorder works, and on the screen recording takes off.
Magisk 14 works, root is.
The camera works, but the photo size is very small.
Sound works, music plays, online music also works.
In general, for me the most difficult is the lack of customization of physical buttons! Aaaaa I can not without the menu button. ))
I will test until the morning.

**Comment by vonico** [comment]
@Oleggluk I tried the google camera and for me it doesn't work

**Comment by Oleggluk** [comment]
@vonico
The standard camera and Snap Camera HDR work for me

**Comment by Oleggluk** [comment]
That's not on time .. An official xposed came out for Android N https://www.xda-developers.com/official-xposed-framework-android-nougat/

**Comment by Spookcity** [comment]
@Oleggluk and @vonico Thanks a lot guys. It is very helpful! Most of these issues I knew about. I didn't know about the photo size though. The camera doesn't work for me on the last build,but I'm not overly concerned as I think that I may have made a mistake. I'm not real sure what the status of GPS is. I'll have to look at the device tree and talk to Tobias.
As far as Xposed for Nougat: Go figure. Isn't that how these things seem to work. I think that getting it to work on Oreo will be much easier than going from Lollipop to Marshmallow though as the changes between M and O are a lot more subtle,but who knows.

**Comment by vonico** [comment]
@Spookcity about GPS. in the build from a couple of days snapchat gets the signal and provides me the filters without issues, so I guess it works. Google maps also recognizes my location without any problems, so location is working here

**Comment by Spookcity** [comment]
@vonico Hmm,interesting. Thanks. So I guess it does work. At least to some extent. That's good. I'm sure there are still issues to be resolved with it though. In time.

_Sent from my Samsung SM-G800 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Oleggluk** [comment]
@Spookcity At night for 9.5 hours the charge decreased by 4%, this is a good result.
Los 15 is already quite stable. But since there are still very few settings, I can not use it every day. After RR, I do not have one million) settings. I return to RR and will experiment with xposed). Thank you, you are going in the right direction).

**Comment by Spookcity** [comment]
@Oleggluk Great to hear! Those are def good results. Tobias is back and he already has a proper fix for the storage issue becasue he is a ninja hehe. It seems as if not a lot is happening with LOS really. They have not done too much in the last little while,so I don't know whats going on with that. Hopefully they will start adding things in the near future though. Time will tell.

**Comment by jimmy999x** [comment]
Greetings to all, I have a query, I bought a Samsung galaxy j7 (2016), excellent device, but unfortunately does not have any rom aosp, I would like to build from 0 device tree, some advice or tutorial?

**Comment by Spookcity** [comment]
Hey @jimmy999x good to see  you around. I hope all is well. As far as your question: I only know of one way to do this,and that is to find a device (or 2) that is as similar as possible to the J7 that already has working device trees. Then you can use that as your starting point. Obviously you can't use their proprietary blobs,but you can extract those from your device with [This](https://github.com/JackpotClavin/Android-Blob-Utility) It will be a lot of debugging and trial and error,but it can be done this way. If there are no devices similar that have device trees available then I really don't know. Good luck!

**Comment by jimmy999x** [comment]
a developer is working for this device, but I would like to do a job on my side, to learn a little more

**Comment by hard-sat** [comment]
**Spookcity**, our great teacher, help please, let's complete Spookcity_Kernel-N_v5.1-1500mhz, good luck to you, and all the best))
I thank

**Comment by Spookcity** [comment]
@jimmy999x Gotcha,well I think the best way is to do what I mentioned...At least it's the only way I know. You will def learn some things if you go this way as it will certainly not be easy.

@hard-sat I will try my best to work on fixing the bizarre frequency with the 1500mhz kernel this week or over the weekend. I cannot promise as I have been rather busy,but I'll try to find some time.

**Comment by Spookcity** [comment]
**AEX-4.6 Highly Optimized with most apps  removed**

This was really only meant as a personal build,but I have decided to share for those who use this ROM and would like to give it a try. **This is not an update to AEX 4.6** I will not be building anymore updates for this ROM. This is simply as the title suggests,a very optimized build with nearly all apps removed. On to some info:

**Uber toolchain 8.x (arm-linux-androideabi)**
**DragonTC 5.0**
**Full O3 (arm,thumb,clang)**
**LTO and Polly**
**Graphite**

**Build Flags**
- fgraphite
- fgraphite-identity
- O3
- mtune=cortex-a7
- mcpu=cortex-a7
- mfpu=neon-vfpv4
- fivopts
- fgcse-las
- funroll-loops
- fira-loop-pressure
- ftree-vectorize
- funsafe-loop-optimizations
- mvectorize-with-neon-quad
- and a lot more

**- The kernel is stock. Nothing special.No special toolchain or build flags. I recommend flashing my kernel for a full "optimized experience"**
**- All apps which do not effect the ROM have been removed as I don't use them**
**- Added Nova Launcher**
**- I needed to take some liberties with some of the code in order to be able to build this with UBER 8.x and DragonTC 5. Ive been running this ROM for days and all seems well,but as always: YOU FLASH AT YOUR OWN RISK**
**- There will be no updates to this.I only built this for me as its the ROM I use**

**Download**
[AEX-4.6_UBERTC8.X-DTC5.0](https://drive.google.com/open?id=0B_rGv18gTmnVOVRZcUxPelJ3a0k)

**Comment by jimmy999x** [comment]
thank you so much, I'll try both

**Comment by Oleggluk** [comment]
@Spookcity It is intriguingly written. Also try this version))

**Comment by Oleggluk** [comment]
@Spookcity How in AEKS-4.6_UBERTC8.X-DTC5.0 write sms? :D

**Comment by Spookcity** [comment]
@Oleggluk Haha,yep,no messaging app either as I always use a 3rd party app. Usually textra. You can easily grab the default messaging app from another ROM though.

_Sent from my Samsung SM-G800F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Oleggluk** [comment]
@Spookcity I already pulled out the application for sms from RR. I can not understand how you like this firmware? Advanced settings resemble Windows 98))). Can you do the same with RR? Applications that I can remove myself, but optimize all sorts of fashionable ones, too. Magisk is better not to build into the firmware, it often has a beta version and it's easier to put it separately.

**Comment by Spookcity** [comment]
@Oleggluk Hah,well we will have to agree to disagree :D AEX is by far my favorite ROM. There's just something about it. It has all of the customization options I need and it runs fantastically for me. Even the "standard" version.
That's the reason there are so many different custom ROM options available though, because we all have different likes and tastes. 

Edit: I perhaps can try to do a RR build with custom toolchains and optimization build flags. I will at least look into it. This build took me a few weeks on and off as its a lot more difficult to build ROMS with these toolchains and build flags.

_Sent from my Samsung SM-G800F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Oleggluk** [comment]
@Spookcity All these additional settings are in the RR and also work fine and it looks better)). Tastes are different, but I still do not understand).
It will be great if you can also do RR. I think we still have a long time to use it, since on the 8 android RR will probably only next year (.

**Comment by Spookcity** [comment]
@Oleggluk I'll certainly look into it. Yeah,there is no O/8.0 branch for RR. I was kinda surprised as most ROMS already have one. Perhaps you've read something and it will indeed be next year.



_Sent from my Samsung SM-G800F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Oleggluk** [comment]
@Spookcity It's just my assumption that something stable will not be until next year.
I restored my applications, made the settings, applied the theme .., now if I do not go into advanced settings, this disk can not be distinguished from RR)). I will give him a chance), I will test a few days if I do not find serious problems for me.

**Comment by Spookcity** [comment]
@Oleggluk Hehe,yeah give it a try. I do really like AEX. I think you're probably right about RR. I mean if they've not even started on the Oreo repo I think it will indeed be some time.

_Sent from my Samsung SM-G800F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Oleggluk** [comment]
@Spookcity And where did the system profiles go?

**Comment by Spookcity** [comment]
@Oleggluk No system profiles on AEX. Some may not like this. I personally do as I never use the profiles.

**Comment by Oleggluk** [comment]
@Spookcity I just recently started using system profiles on the RR. During wi-fi activation, the network mode was switched to E, when wi-fi was turned off, the network mode was switched to 4G, it is very convenient and economical. And in AEX there are no profiles and there is not even a quick setting for switching the network (this is minus (

**Comment by Spookcity** [comment]
@Oleggluk Ahh,I see. This would be useful in that situation. I never fully understood using system profiles,but for a situation like that it does indeed make sense and sound useful.

**Comment by Oleggluk** [comment]
@Spookcity I do not know how you did it, but it's an absolute record for all three years of using this phone.
![screenshot_20171014-144248](https://user-images.githubusercontent.com/27913216/31575400-dbcbe558-b0ee-11e7-9d31-13189c42065c.png)

**Comment by Spookcity** [comment]
@Oleggluk Wow, I assume this is battery? That is indeed great! I also have very good battery life on AEX in general,but it is also better for me with my "optimized" build. I can't really say why. I suppose just some of the build flags must improve it in some way...Or I accidentally discovered something when I needed to edit some of the code to build with these optimizations and toolchains :D

**Comment by Oleggluk** [comment]
@Spookcity "@Oleggluk Wow, I assume this is battery?"
This is more than 9 hours of screen work on AEKS-4.6_UBERTC8.X-DTC5.0 with my usual use. Such a result was never on one firmware. Now I have a new favorite among the firmware))

**Comment by Spookcity** [comment]
@Oleggluk That is really amazing results! I will have try check my battery more closely. I just know that I do have great battery life with this ROM....I told you to give it a chance hehe

**Comment by Oleggluk** [comment]
@Spookcity And the memory of the calendar (com.providers.calendar) for what purpose left? It also works only with the standard calendar. Or do you need something else?

**Comment by Spookcity** [comment]
@Oleggluk I think,but may be wrong that it was needed for another package to build correctly. There was some reason I left it,but can't specifically remember right now. I think that's what you're asking. If not sorry :D

_Sent from my Samsung SM-G800F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Oleggluk** [comment]
@Spookcity understandably thank you. Any interesting news about Los15 or more?

**Comment by Spookcity** [comment]
@Oleggluk I've been using LOS 15 for about a week. For me it runs very nicely. The big things that still don't work that I know are NFC,GPS and video recording. I don't think Tobias has made any recent commits to the device repos,so if I have some time this week I'm going to try to lend a hand and see if I can at least figure one of those out. Everything else works great for me.
Then I'm going to try to build the Oreo version of my favorite ROM....AEX :D

_Sent from my Samsung SM-G800F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Oleggluk** [comment]
@Spookcity Oh yeah, I saw a little on the other phone AEX v5 alfa, they are working on it. There even there are a few additional settings). Only translation into Russian is almost not (.But I think in the future they will make a translation.) Also it would be interesting to try a super-duper)) version of you as a version of AEKS-4.6_UBERTC8.X-DTC5.0

**Comment by Spookcity** [comment]
@Oleggluk Yeah,I downloaded the AEX sources yesterday. Maybe sometime this week I will try to build and see how it goes. Also,I will certainly try to do an optimized build of an oreo ROM at some point.

@hard-sat I think and hope I have corrected the strange frequency issue on the 1500mhz version of my kernel. Could you let me know if its fixed so I can upload this version to XDA and start working on the next version.
Download - [Spookcity_Kernel-N_v5.1-1500mhz](https://drive.google.com/open?id=0B_rGv18gTmnVYnBTODhoQjBNMjg)

**Comment by hard-sat** [comment]
Everything is great !!! I THANK !!!  )))

**Comment by Oleggluk** [comment]
@Spookcity Ever wondered about the re-partitioning of memory? The system partition on the stock firmware takes 5GB! And on custom firmware about 1GB. Whichever patch to do, to return part of the system partition to the Data section. I hope after the translation of my idea is clear))

**Comment by Spookcity** [comment]
@Oleggluk I do understand what you're saying. I've honestly never thought about this,but you're correct about the huge amount of space that the stock firmware uses. I can certainly look into it. Its an interesting idea. If it's possible I can't say. If you come across anything interesting related to this please do share. I'll try to search a bit when I have some time.
I assume it would involve creating a pit file to flash.

_Sent from my Samsung SM-G800F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Oleggluk** [comment]
@Spookcity I found one topic where there is a lot of information and instructions about it. But it is in Russian (http://4pda.ru/forum/index.php?showtopic=544998). There are a lot of instructions for different processors, but unfortunately I did not see anything for our processor ((., When I have time I'll look more closely.

**Comment by Oleggluk** [comment]
@Spookcity There is nothing useful for Exynos processors to markup memory.
The only phrase with a mention is this:
"Users of smartphones based on Exynos processors are less fortunate - they will have to develop a kernel with already re-allocated memory."
And I also looked in Titanium Backup, that in the system section 2.11gb and freely only 1.37gb. Internal memory + media 12.7gb. We have nothing to increase). In general, stupid is an idea.

**Comment by Spookcity** [comment]
@Oleggluk Haha.ok. Thanks for the info though. It was an interesting idea...I suppose for other phones. It's something I had not thought of before.

**Comment by Oleggluk** [comment]
@Spookcity One fat minus in AEX is. I just can not install ViperFx. Swears at not working / not suitable BusyBox. I installed different versions of BusyBox in different sections and different ways. I installed ViperFx in many ways, from the usual apk to installing exclusive archives through twrp. Does not want to install / run the driver ((. Is this a common AEX problem or only an optimized version?

**Comment by Spookcity** [comment]
@Oleggluk Interesting. I always use viper as well,but haven't installed it recently as I've been jumping from ROM to ROM. I'm sure I've installed it on AEX before and I don't see why it would be an issue... On the "normal" version or the optimized version. I will try to install it later and see if I can figure out what the problem might be..Oh,you do mean Viper4Android right? Or is this something else?

_Sent from my Samsung SM-G800F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Oleggluk** [comment]
@Spookcity Yes, I'm talking about Viper4Android)
I've never had problems with it on other firmware before.
I will wait for results.

**Comment by Spookcity** [comment]
@Oleggluk OK,thanks. That would indeed be an issue for me as well cause I use it too. Will report back later today with my findings.

_Sent from my Samsung SM-G800F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Spookcity** [comment]
@Oleggluk OK,I had some time.. You are correct it will not install saying a busybox error. I thought that I may have messed something up with my optimized version of AEX,so I tried the standard version. Same error. I am really unsure what the deal is. I also tried a few different versions of busybox without success. There is also a Magisk module for viper,but I kept getting a "process error" when trying to download and install. I know that I installed it on AEX before,but more than likely an older release. There has to be some fix as this would be a deal breaker for me. I will try to figure it out whenever I have some time.

**Comment by Oleggluk** [comment]
@Spookcity Ok. I will know that this is not only my problem. I already broke my head with this. I hope this can be fixed.

**Comment by Spookcity** [comment]
@Oleggluk 

![](https://i.imgur.com/Z1eG5z6.png)

OK, I got it working. I forgot,I always use [A.R.I.S.E.](https://www.google.nl/amp/s/forum.xda-developers.com/android/software/r-s-e-sound-systems-auditory-research-t3379709/amp/)
This will install V4A and the driver. The thread is kinda a mess and its not the easiest to install as you need an arise.prop so it knows what to install. Plus there are many versions. I only ever install the core and viper. I'm not sure of another way right now. If you want to install it and can't figure it out I'll post my prop and such later when I'm home. 

Edit:
I should also mention that Viper does not process unless you set FX compatible mode to compatible in V4A settings.It's always been this way for me with ARISE. Not sure why,but it doesn't seem to effect anything.

_Sent from my Samsung SM-G800F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Oleggluk** [comment]
@Spookcity There, the devil himself will break his leg. I need help). Wow! 300MB. I did not understand, are these modules for Magisk? I refused the Magisk modules, because after the activation of any module, the ability to edit the system and programs working with the system is limited.

**Comment by Spookcity** [comment]
@Oleggluk I think there is a magisk module,but I don't use that. I think the 300mb is for a full install. Could be wrong though,but there are many possible things to install. I install core,viper and viper profiles only. It really is a nice sound mod,just a bit confusing. To make it even more exciting I you need to dirty flash your ROM again. Then flash ARISE. I will post my arise.prop along with the version I installed. Give me a few.

_Sent from my Samsung SM-G800F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Spookcity** [comment]
@Oleggluk Ok,download [This file](https://drive.google.com/open?id=0B_rGv18gTmnVbzVlVEJneExVamM) and place it in the root of your internal storage. This will only install the core and V4A and V4A profiles. I installed the latest build from [Here](https://androidfilehost.com/?w=profile&uid=24549084345925777) "ARISE+Magnum+Opus+20170918+Stock+Edition.zip" The zip can go anywhere on  your phone,but it will look for  the arise.prop in your internal storage. Then you will need to dirty flash your ROM then you can flash ARISE and all should be good. Just remember to set the FX mode to compatible.

The arise.prop basically just tells the installer what to installer. You can obviously open it up and have a look and edit things if you want more. I used to install a few more things as well,but couldnt remember what as its been awhile,so I just went mininal.

**Comment by Oleggluk** [comment]
@Spookcity  God, how is it all difficult, I already got a headache)). Thank you! without you I would never understand.

**Comment by Spookcity** [comment]
@Oleggluk Hah,you're most welcome. The thing with ARISE is that the XDA thread is more confusing than anything. It is really not layed out very well at all and then people keep posting different versions on every page. Its a mess. Let me know if you need more help. I am glad to try.

**Comment by Oleggluk** [comment]
@Spookcity Oh yeah! working! everything is super! and profiles are interesting. Generally elegant! Thank you!!!

**Comment by Spookcity** [comment]
@Oleggluk Great! Glad to hear. I've used ARISE for awhile now..off and on and really like it. Always glad 
 when I'm able to help out as well

**Comment by Oleggluk** [comment]
@Spookcity In the theme of Los14.1 there was today an assembly with some patch: "Build contains latest wpa_supplicant patches." What is this patch? Too I want))

**Comment by vonico** [comment]
Hey @Spookcity 
I just saw there is a new Oreo branch in AEX's github. Do you think you will have time this week to look into it and possibly build a test ROM? I'm excited to see this ROM being updated :)

**Comment by Spookcity** [comment]
@Oleggluk Hmm,I haven't read anything about this. I'm unsure what that's all about. I'll have to do a bit of research. I would have to assume its a security patch as I think the main purpose of the wpa_supplicant is to control keys and other things related to the WiFi driver.
What else the patch would be for I've no idea.

_Sent from my Samsung SM-G800F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by vonico** [comment]
Hey @Spookcity
I just saw there is a new Oreo branch in AEX's github. Do you think you will have time this week to look into it and possibly build a test ROM? I'm excited to see this ROM being updated :)

**Comment by Spookcity** [comment]
@vonico I hope so. It is in my plans to try to build this week or over the weekend. Not sure how easy or hard it may be. I will post it here first,so stay tuned!

_Sent from my Samsung SM-G800F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Oleggluk** [comment]
At AEKS-4.6_UBERTC8.X-DTC5.0, one thing annoys me. For security purposes, the "install" button is not active in this firmware when there is a filter on top of the screen or any information is displayed on top of all windows. I rebuilt PackageInstaller.apk and disabled this protection. I did it for myself, but it's still possible for somebody else to interfere. Download and replace PackageInstaller.apk https://yadi.sk/d/0CnumF-23NqSsz by the system / priv-app / PackageInstaller (Set File Permission (644) "Г")
Just in case, save the original file.

**Comment by Spookcity** [comment]
@Oleggluk That's fantastic! Thank you! I will give this a go.

Update:
It works great. Good job and thanks again @Oleggluk 

_Sent from my Samsung SM-G800F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Oleggluk** [comment]
Someone uses a fingerprint. I found this module "Fingerprint Scanner Booster" for magisk. It increases the priority of the fingerprint process in the system. Hah, maybe it's a coincidence, but for the whole day I did not have any problems with the fingerprint, it works great. I would like to have someone else try it, especially if someone has trouble working on a fingerprint. To see if it really works or not.
@Spookcity If this module really helps in the work of a fingerprint, is it possible to add it not as a module, but at the system level in the new firmware builds? There it is written what code it uses.
https://forum.xda-developers.com/apps/magisk/module-fingerprint-scanner-booster-t3688637

**Comment by Spookcity** [comment]
@Oleggluk That's a nice find! I don't use the fingerprint scanner so I can't really test...or at least I wouldn't notice a difference if I did. 
After just a quick glance at the link you posted about the module it seems as if this could be implemented in the kernel. I'll have to read through that a bit more though.

_Sent from my Samsung SM-G800F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Spookcity** [comment]
I've update my kernel on XDA to v6.0 (same as 5.1) Hopefully over the next few weeks I have the time to look into adding ZRAM,possibly implementing the fingerprint boost that @Oleggluk has found,along with other that ideas I have.

Also,lets continue this over [Here](https://github.com/Spookcity/ROMS-G800F/issues/23)
